services:
  postgres:
    image: postgres:17.4
    container_name: postgres_weather_container
    restart: no
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_CONTAINER_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    tty: true
    stdin_open: true

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  weather_service:
    build:
      context: .
      target: build
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: weather_service
    # Mounting source is useful for dev; remove in production
    volumes:
      - ./cmd:/app/cmd
      - ./internal:/app/internal
      - ./migrations:/app/migrations
      - ./static:/app/static
    ports:
      - ${CONTAINER_PORT_MAPPING}
    depends_on:
      postgres:
        condition: service_healthy