// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/confirm/{token}": {
            "get": {
                "description": "Confirms a subscription using the token sent in the confirmation email.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Confirm email subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Confirmation token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Subscription confirmed successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Token not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/subscribe": {
            "post": {
                "description": "Subscribes an email to weather updates for a specific city with the given frequency.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Subscribe to weather updates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email address to subscribe",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "City for weather updates",
                        "name": "city",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "enum": [
                            "hourly",
                            "daily"
                        ],
                        "type": "string",
                        "description": "Frequency of updates (hourly or daily)",
                        "name": "frequency",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Subscription successful. Confirmation email sent.",
                        "schema": {
                            "$ref": "#/definitions/internal_server_handlers_subscription.Subscription"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Email already subscribed",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal api error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/unsubscribe/{token}": {
            "get": {
                "description": "Unsubscribes an email from weather updates using the token sent in emails.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Unsubscribe from weather updates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unsubscribe token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Unsubscribed successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Token not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/weather": {
            "get": {
                "description": "Returns the current weather forecast for the specified city using WeatherAPI.com.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weather"
                ],
                "summary": "Get current weather for a city",
                "parameters": [
                    {
                        "type": "string",
                        "description": "City name for weather forecast",
                        "name": "city",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful operation - current weather forecast returned",
                        "schema": {
                            "$ref": "#/definitions/weather.Weather"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "City not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_server_handlers_subscription.Subscription": {
            "type": "object",
            "properties": {
                "city": {
                    "description": "City for weather updates",
                    "type": "string"
                },
                "confirmed": {
                    "description": "Whether the subscription is confirmed",
                    "type": "boolean"
                },
                "email": {
                    "description": "Email address",
                    "type": "string"
                },
                "frequency": {
                    "description": "Frequency of updates\nEnum: hourly, daily",
                    "type": "string"
                }
            }
        },
        "weather.Weather": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "Weather description",
                    "type": "string"
                },
                "humidity": {
                    "description": "Current humidity percentage",
                    "type": "number"
                },
                "temperature": {
                    "description": "Current temperature",
                    "type": "number"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Weather forecast operations",
            "name": "weather"
        },
        {
            "description": "Subscription management operations",
            "name": "subscription"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so client can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Weather Forecast API",
	Description:      "Weather API application that allows users to subscribe to weather updates for their city.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
