basePath: /api
definitions:
  model.Subscription:
    properties:
      city:
        type: string
      confirmed:
        type: boolean
      email:
        type: string
      frequency:
        type: string
      token:
        type: string
    type: object
  model.Weather:
    properties:
      description:
        type: string
      humidity:
        type: number
      temperature:
        type: number
    type: object
  response.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
  description: Weather API application that allows users to subscribe to weather updates
    for their city.
  title: Weather Forecast API
  version: 1.0.0
paths:
  /subscription/confirm/{token}:
    get:
      description: Confirms a subscription using the token from the confirmation email.
      parameters:
      - description: Confirmation token
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Subscription confirmed successfully
          schema:
            type: string
        "400":
          description: Invalid token
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Token not found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Confirm subscription
      tags:
      - subscription
  /subscription/subscribe:
    post:
      consumes:
      - application/json
      description: Subscribes an email to weather updates for a city with a frequency.
      parameters:
      - description: Subscription request
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/model.Subscription'
      produces:
      - application/json
      responses:
        "200":
          description: Subscription request accepted. Confirmation email sent.
          schema:
            $ref: '#/definitions/model.Subscription'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "409":
          description: Email already subscribed
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Subscribe to weather updates
      tags:
      - subscription
  /subscription/unsubscribe/{token}:
    get:
      description: Unsubscribes an email using the provided token.
      parameters:
      - description: Unsubscribe token
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Unsubscribed successfully
          schema:
            type: string
        "400":
          description: Invalid token
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Token not found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Unsubscribe from weather updates
      tags:
      - subscription
  /weather:
    get:
      consumes:
      - application/json
      description: Returns the current weather for the specified city using WeatherAPI.com.
      parameters:
      - description: City name
        in: query
        name: city
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Current weather returned
          schema:
            $ref: '#/definitions/model.Weather'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: City not found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Get current weather for a city
      tags:
      - weather
schemes:
- http
- https
swagger: "2.0"
tags:
- description: Weather forecast operations
  name: weather
- description: Subscription management operations
  name: subscription
